import{i as d,a as b,S as v}from"./assets/vendor-64b30587.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const m=document.querySelector(".form"),g=document.querySelector(".gallery"),i=document.querySelector(".load-btn"),r=document.querySelector(".loader");let h,n,u;m.addEventListener("submit",w);i.addEventListener("click",S);function w(o){o.preventDefault(),g.innerHTML="",r.classList.remove("hidden"),u=m.elements.q.value.trim(),u!==""?p().then(e=>{e.hits.length===0?(d.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),i.classList.add("hidden")):(n=1,f(e.hits),i.classList.remove("hidden"))}).catch(e=>console.log(e)).finally(()=>{r.classList.add("hidden")}):(d.show({message:"Please fill out the search field",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),r.classList.add("hidden")),m.reset()}function C(){const o=document.querySelector(".gallery-item"),{height:e}=o.getBoundingClientRect();return e}function S(){console.log(n),i.classList.add("hidden"),r.classList.remove("hidden");const o=C();p().then(e=>{e.totalHits-n*40<=0?(d.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#03a9f4",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),i.classList.add("hidden")):(n+=1,f(e.hits),i.classList.remove("hidden"),window.scrollBy({top:o*2,left:0,behavior:"smooth"}))}).catch(e=>console.log(e)).finally(()=>{r.classList.add("hidden")})}const p=async function(){const o="42001706-084c655b89d9d100c07cefb17",e="https://pixabay.com/api/";return(await b.get(e,{params:{key:o,q:u,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:40}})).data};function f(o){const e=o.map(a=>{const{webformatURL:c,largeImageURL:t,tags:s,likes:l,views:y,comments:F,downloads:L}=a;return`<li class="gallery-item">
                <a class="gallery-link" href=${t}>
                <img src=${c} alt="${s}" /></a>
                    <ul class="image-desc">
                        <li class="image-desc-item"><p>Likes</p><p>${l}</p></li>
                        <li class="image-desc-item"><p>Views</p><p>${y}</p></li>
                        <li class="image-desc-item"><p>Comments</p><p>${F}</p></li>
                        <li class="image-desc-item"><p>Downloads</p><p>${L}</p></li>
                    </ul>
            </li>`});q(e),h.refresh()}function q(o){o=o.join(""),g.insertAdjacentHTML("beforeend",o),h=new v(".gallery a",{captionDelay:250,captionsData:"alt"})}
//# sourceMappingURL=commonHelpers.js.map
