import{i as m,a as b,S as w}from"./assets/vendor-64b30587.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function l(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=l(t);fetch(t.href,s)}})();const u=document.querySelector(".form"),g=document.querySelector(".gallery"),r=document.querySelector(".load-btn"),a=document.querySelector(".loader");let h,d=1,c;u.addEventListener("submit",v);r.addEventListener("click",S);async function v(o){o.preventDefault(),g.innerHTML="",a.classList.remove("hidden"),r.classList.add("hidden"),c=u.elements.q.value.trim(),d=1;try{if(c!==""){const e=await p(c);e.hits.length===0?m.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}):(f(e.hits),r.classList.remove("hidden"))}else m.show({message:"Please fill out the search field",position:"topRight",backgroundColor:"#EF4040",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),a.classList.add("hidden")}catch(e){console.log(e)}finally{a.classList.add("hidden"),u.reset()}}function C(){const o=document.querySelector(".gallery-item"),{height:e}=o.getBoundingClientRect();return e}async function S(){r.classList.add("hidden"),a.classList.remove("hidden");const o=C();d+=1;try{const e=await p();f(e.hits),r.classList.remove("hidden"),window.scrollBy({top:o*2,left:0,behavior:"smooth"}),e.totalHits-d*40<=0&&(m.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#03a9f4",titleColor:"#FFFFFF",messageColor:"#FFFFFF"}),r.classList.add("hidden"))}catch(e){console.log(e)}finally{a.classList.add("hidden")}}const p=async function(){const o="42001706-084c655b89d9d100c07cefb17",e="https://pixabay.com/api/";return(await b.get(e,{params:{key:o,q:c,image_type:"photo",orientation:"horizontal",safesearch:"true",page:d,per_page:40}})).data};function f(o){const e=o.map(l=>{const{webformatURL:n,largeImageURL:t,tags:s,likes:i,views:y,comments:F,downloads:L}=l;return`<li class="gallery-item">
                <a class="gallery-link" href=${t}>
                <img src=${n} alt="${s}" /></a>
                    <ul class="image-desc">
                        <li class="image-desc-item"><p>Likes</p><p>${i}</p></li>
                        <li class="image-desc-item"><p>Views</p><p>${y}</p></li>
                        <li class="image-desc-item"><p>Comments</p><p>${F}</p></li>
                        <li class="image-desc-item"><p>Downloads</p><p>${L}</p></li>
                    </ul>
            </li>`});q(e),h.refresh()}function q(o){o=o.join(""),g.insertAdjacentHTML("beforeend",o),h=new w(".gallery a",{captionDelay:250,captionsData:"alt"})}
//# sourceMappingURL=commonHelpers.js.map
